
# Current status of development - V01:

#Brands in scope
BRANDS:
  # - fast_duck
  # - gold_plane
  - precious_liquid


# for predious_liquid - get rid of laura & alex
TOUCHPOINTS:
  - tom
  # - laura
  - lisa
  - mary
  - fiona
  - marc
  # - alex


TARGET: TARGET_VOL_SO

SEASONALITY_VARIABLES_BASE:
 - is_january
 - is_february
 - is_march
 - is_april
 - is_may
 - is_june
 - is_july
 - is_august
 - is_september
 - is_october
 - is_november
 - is_december
 - is_last_week

#  - christmas
#  - is_penultimate_week
#  - is_year_end_week

CONTROL_VARIABLES_BASE:
   - distribution
   - covid
   - promotion
   - epros
   - off_trade_visibility

#definition of price period ends for calculation of discount price reference levels
PRICE_PERIOD_1_END: 201905
PRICE_PERIOD_2_END: 202113








