MAX_LAG: 8

#not functional yet
ADSTOCK_FUNCTION_TYPE:
  tom: 'impression_spendings'
  laura: 'impression_spendings'
  lisa: 'impression_spendings'
  mary: 'impression_spendings'
  jack: 'impression_spendings'
  fiona: 'impression_spendings'
  marc: 'impression_spendings'
  alex: 'impression_spendings'

SHAPE_SHIFT_PRIOR:
  tom: 1
  laura: 1
  lisa: 1
  mary: 1
  fiona: 1
  marc: 0
  alex: 0


SHAPE_THRESHOLD_VALUE:
  tom: 7000
  laura: 7000
  lisa: 5000
  mary: 3500
  fiona: 5000
  marc: 50000
  alex: 15000

SHAPE_SATURATION_VALUE:
  tom: 55000
  laura: 60000
  lisa: 50000
  mary: 72500
  fiona: 118347
  marc: 741429
  alex: 159942