
#Definition of touchpoints and order of calling
TOUCHPOINTS:
  - touchpoint_2
  - touchpoint_3
  - touchpoint_4

#define seasonality variables - order due to data generation model
SEASONALITY_VARIABLES_BASE:
 - april
 - august
 - december
 - february
 - january
 - july
 - june
 - march
 - may
 - november
 - october
 - september
#  - christmas
#  - is_penultimate_week
#  - is_year_end_week

CONTROL_VARIABLES_BASE:
  - promotion

#defining normalization steps of touchpoints
#the normalization steps will follow the order below:
NORMALIZATION_STEPS_TOUCHPOINTS:

  touchpoint_2: ['mean_across_brands']
  touchpoint_3: ['mean_across_brands']
  touchpoint_4: ['mean_across_brands']
  

#defining normalization steps of touchpoints
#the normalization steps will follow the order below:
NORMALIZATION_STEPS_SALES:
  sales: ['mean_across_brands', 'logp1']

