
#Definition of touchpoints and order of calling
TOUCHPOINTS:
  # - touchpoint_2
  - touchpoint_3
  - touchpoint_4

TARGET: sales

#define seasonality variables - order due to data generation model
SEASONALITY_VARIABLES_BASE:
 - april
 - august
 - december
 - february
 - january
 - july
 - june
 - march
 - may
 - november
 - october
 - september
#  - christmas
#  - is_penultimate_week
#  - is_year_end_week

CONTROL_VARIABLES_BASE:
  - promotion



